[workspace]

members = ["projects/*"]
default-members = [
    "projects/wolfram-serde",
    "projects/wolfram-lib",
    "projects/wolfram-cli",
]

exclude = [
    "projects/.DS_Store",
    "projects/project-logo",
]

[profile.release]
lto = true
